coverage:
  status:
    patch: false
    project:
      default:
        threshold: 50%
  ignore:
    - "run_brer/tests/.*"
    - "setup.py"
    - "versioneer.py"
comment:
  layout: "header"
  require_changes: false
  branches: null
  behavior: default
  flags: null
  paths: null
